channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      # Azure ML / MLflow
      - azure-ai-ml>=1.13.0
      - mlflow==2.8.1
      - mlflow-skinny==2.8.1

      # Core ML stack (MATCHES HF ENV)
      - scikit-learn==1.6.0
      - pandas>=2.1,<3
      - numpy>=1.23,<2
      - scipy>=1.10,<2
      - joblib==1.5.1
      - pyarrow>=10,<15
      - matplotlib>=3.7
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-client
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-collector